# Generated by Django 3.2.18 on 2023-04-13 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdata',
            old_name='phone',
            new_name='subject',
        ),
    ]
