# Generated by Django 3.2.18 on 2023-04-20 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
