# Generated by Django 3.2.18 on 2023-04-20 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
