# Generated by Django 3.2.18 on 2023-04-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('location', models.TextField()),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
